spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mini_project?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    username: root
    password: root

